---
title: "(optional) recap LMs and basic plots"
output: html_document
date: "2026-03-05"
---

## Recap of Linear Models & Basic Plots (optional)


### Linear Regression Models
Linear regression models are a commonly used type of linear model, which are particularly useful when both the response and predictor variables are continuous. We use linear regression models to quantify the relationship between these two variables so that we can identify trends and make predictions from the data.


Linear regression models fit a straight line relationship between the response variable and continuous explanatory variable, which can be shown as the equation:
(insert equation for linear regression model)


To code a linear regression model, we can use the following syntax:
(write as code) specificModelName <- lm(responseVariable ~ explanatoryVariable, data = yourDataset)


**Tip:**
When naming models or other objects in R, try to use specific names so you know what your object is explicitly. Using short names like model1, model2, etc. can get confusing.


**Frequent Mistake:**
R cannot handle spaces in object names. There are a few options for alternative syntax, we would recommend using camelCase where letters are capitalised to indicate new words (e.g. specificModelName), or using an underscore to connect words (e.g. specific_model_name).


If using camelCase, remember that R is case sensitive - if your object is named specificModelName, but you call specificmodelname, R will show an error:
Error: object ‘specificmodelname’ not found.


To view the output of a linear regression model, we can use the summary() function:
(write as code) summary(specificModelName)
This will show a lot of information (which is useful to familiarise yourself with), but for this workshop, we are primarily interested in the Coefficients table.


This table will have one row for each coefficient in the model - two rows for a simple linear regression model: the Intercept and the Slope.
The Intercept estimate represents the predicted value of the response variable when the explanatory variable is zero.
The Slope () estimate is proportional to the correlation coefficient between the response variable and explanatory variable, scaled by the ratio of standard deviations. Put simply, this estimate represents the strength (value) and direction (positive or negative) of the relationship between the response and explanatory variables.


The Coefficient table also shows the details for a t-test, which tells us whether or not the slope and intercept are significantly different from zero.
	Std. Error - how far observations sit from the regression line.
	t value - the estimate divided by the standard error.
  Pr(>|t|) - the p-value, used to inform the probability of observing this result if the true coefficient was zero.


**Tip:**
When we plot a line of best fit, this reflects the mean, variance, and correlations in your dataset. Knowledge on these model coefficients will help you better understand the plots and visualisations we do later in this workshop.


### ANOVA Models
What happens if your explanatory variable is categorical, rather than continuous? This is where ANOVA models come in, or the **AN**alysis **O**f **VA**riance across the means of different groups or categories. An ANOVA is a useful type of linear model, particularly when the response variable is continuous, and the explanatory variable is categorical.


Coding an ANOVA is essentially the same as a linear regression model - we still use the lm() function to fit the relationship between a response and explanatory variable. However, now that the explanatory variable is categorical, the slope represents the difference between group (category) means.


(write as code) specificModelName <- lm(continuousResponse ~ categoricalExplanatory, data = yourDataset)


As before, we can use the summary() function to check the model output and view the Coefficients table (which will be laid out in the same way as a linear regression model output).
(write as code) summary(specificModelName)
Despite looking the same, there are some differences for an ANOVA output:
The Intercept is the mean of the first category.
The Slope is the difference between the mean of the first category and this (named) category.


While the summary() function can be used to assess the differences between specific categories, the anova() function can tell us whether or not the categorical explanatory variable as a whole has a significant effect on the response variable.
(write as code) anova(specificModelName)
The output of the anova() function also provides a table, which lists the following statistics:
Df - refers to the number of categories and observations.
Sum Sq & Mean Sq - measures of variance between or within categories. 
F-value - the ratio of explained variance to unexplained variance (a higher F-value indicates the categorical variable has a significant effect). 
Pr(>F) - the p-value, used to inform the probability of observing this F-value if there was no true difference between the categories.


**Tip:**
Use summary() if you are interested in the category means and differences of the explanatory variable.
Use anova() if you are interested in the overall significance of the explanatory variable on the response variable.


If you are interested in further linear models, you can find resources here:
	Linear Models: Multiple explanatory variables
	Linear Models: Multiple variables with interactions
**This additional content is optional, and is not necessary to complete this workshop.**


## Basic Plots


### Scatter Plots
A scatter plot can be used when you want to visualise the relationship between two continuous variables.


Plotting raw data with a scatter plot allows you to identify trends in the data, including direction and strength of the relationship between the variables. You can also spot outlier observations that deviate from the general pattern, and the shape of the data can help decide whether a linear or non-linear model is appropriate for your dataset.


However, if you have a very large dataset, points on a scatter plot can overlap so much that the plot becomes messy and difficult to interpret.


**Walkthrough Task**
Let’s start by opening our dataset. Use the … function to open the … dataset:
(code opening dataset)


**Note:**
See **Reading and Resources** for the raw versions of the data files used through this workshop. You are not expected to use these, but seeing the raw format might help you to better understand the data we are working with.


Although the data in this workshop has been tidied for you, it is good practice to check the data. Let’s assess the type of data we are working with by using the … function:
(code to check variable type)


To plot a simple scatter plot of our data, we can use the plot() function:
(write as code) plot(myDataframe$variable1, myDataframe$variable2)


**Where people typically make mistakes:**
If you just press plot() without describing specific variables in your dataset, you will end up with a messy and overwhelming visualisation. Use $ and specify the specific variables you want to compare.


### Histograms
Histograms are used to visualise the distribution on a single continuous variable. This is done by splitting the range of values into intervals, called bins, and calculating the frequency of data points that sit in each interval.


Histograms can be particularly useful to check whether your data is normally distributed or skewed, to view the variance (or spread) of your data, and to identify gaps in the data which may suggest issues with data collection.


Histograms do not show us the relationship between variables. However, we can plot two histograms for two variables we want to compare so that we can assess the distributions of the two variables.


**Walkthrough Task**
Using the same dataset, we will now plot a simple histogram of our … variable using the hist() function:
(write as code) hist()


We can then plot a second histogram of … variable for visual comparison:
(write as code) hist()


### Boxplots
What is a box plot and when to use one... Benefits and limitations...


**Walkthrough Task**
Code to plot a boxplot


### Saving Plots & Visualisations
How to save a plot...


## Reading & Resources
Any additional content (e.g. from MQB)


https://www.datacamp.com/doc/r/parameters?dc_referrer=https%3A%2F%2Fwww.google.com%2F


Raw versions of datasets
















