# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

name: bookdown.yaml

permissions: read-all

jobs:
  bookdown:
    runs-on: ubuntu-latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: false
          r-version: renv
          
      # System dependencies are not taken care of (yet) by r-lib/actions/setup-renv
      # We rely on pak and explicitly install them for the renv.lock packages
      # We could use pak-based installation for renv, which includes system
      # requirements, but would have to handle the pak cache explicitly
      # See https://github.com/r-lib/actions/issues/785
      - name: Setup pak to install system dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: jsonlite, processx
          dependencies: NA
          cache-version: 'sysreqs-1' # ensure keys are not shared with the renv cache
      - name: Install system dependencies
        run: |
          (sysreqs_cmds <- pak::pkg_sysreqs(names(jsonlite::read_json("renv.lock")$Packages), dependencies = FALSE))
          # inspired by pkgdepends:::sysreqs_install
          lapply(unlist(sysreqs_cmds[c("pre_install", "install_scripts", "post_install")]), function(cmd) {
            processx::run("sudo", c("sh", "-c", cmd))
          })
        shell: Rscript {0}

      - uses: r-lib/actions/setup-renv@v2

      - name: Cache bookdown results
        uses: actions/cache@v4
        with:
          path: _bookdown_files
          key: bookdown-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-

      - name: Build site
        run: bookdown::render_book("index.Rmd", quiet = TRUE)
        shell: Rscript {0}

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: _book
